-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.admin_users (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Note: You should manually insert a user here using the generated bcrypt hash from python passlib for the pmv
-- INSERT INTO admin_users (username, hashed_password) VALUES ('admin', '$2b$12$YOUR_BCRYPT_HASH_HERE');


CREATE TABLE IF NOT EXISTS public.schema_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    column_name VARCHAR(255) NOT NULL,
    is_required BOOLEAN DEFAULT TRUE NOT NULL,
    data_type VARCHAR(50) DEFAULT 'str' NOT NULL,
    min_value DOUBLE PRECISION,
    max_value DOUBLE PRECISION,
    missing_value_code VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Opcional: Proteger las tablas con Row Level Security si se desea en el futuro (no necesario para backend S2S con Service Key)
-- ALTER TABLE public.schema_rules ENABLE ROW LEVEL SECURITY;
