-- Clean up old tables for a clean state in presentation
DROP TABLE IF EXISTS public.indicator_dependencies;
DROP TABLE IF EXISTS public.indicators;
DROP TABLE IF EXISTS public.schema_rules;
DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.admin_users;

-- Table for users with roles
CREATE TABLE public.users (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'foundation' NOT NULL, -- 'admin' or 'foundation'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed users (PLAIN TEXT for emergency presentation bypass)
INSERT INTO public.users (username, hashed_password, role) 
VALUES 
('admin', 'admin123', 'admin'),
('foundation', 'foundation123', 'foundation')
ON CONFLICT (username) DO NOTHING;

CREATE TABLE public.schema_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    column_name VARCHAR(255) UNIQUE NOT NULL,
    is_required BOOLEAN DEFAULT TRUE NOT NULL,
    data_type VARCHAR(50) DEFAULT 'str' NOT NULL,
    min_value DOUBLE PRECISION,
    max_value DOUBLE PRECISION,
    missing_value_code VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed Dummy Schema Rules (Clinical Fields)
INSERT INTO public.schema_rules (column_name, data_type, is_required, min_value, max_value)
VALUES 
('peso_kg', 'float', true, 0.5, 10.0),
('talla_cm', 'float', true, 20.0, 80.0),
('edad_gestacional_semanas', 'int', true, 24, 42),
('perimetro_cefalico_cm', 'float', false, 20.0, 50.0)
ON CONFLICT (column_name) DO NOTHING;

-- Clinical Indicators Table
CREATE TABLE public.indicators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    description TEXT,
    calculation_formula TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Dependency Mapping
CREATE TABLE public.indicator_dependencies (
    indicator_id BIGINT REFERENCES public.indicators(id) ON DELETE CASCADE,
    rule_id BIGINT REFERENCES public.schema_rules(id) ON DELETE CASCADE,
    PRIMARY KEY (indicator_id, rule_id)
);

-- Seed Dummy Indicators
INSERT INTO public.indicators (name, description, calculation_formula)
VALUES 
('IMC Neonatal', 'Índice de Masa Corporal ajustado para prematuros.', '(peso_kg) / (talla_cm / 100)^2'),
('Crecimiento Cefálico', 'Relación entre perímetro y edad gestacional.', 'perimetro_cefalico_cm / edad_gestacional_semanas')
ON CONFLICT (name) DO NOTHING;

-- Link dependencies
INSERT INTO public.indicator_dependencies (indicator_id, rule_id)
SELECT i.id, r.id FROM public.indicators i, public.schema_rules r
WHERE i.name = 'IMC Neonatal' AND r.column_name IN ('peso_kg', 'talla_cm')
ON CONFLICT DO NOTHING;

INSERT INTO public.indicator_dependencies (indicator_id, rule_id)
SELECT i.id, r.id FROM public.indicators i, public.schema_rules r
WHERE i.name = 'Crecimiento Cefálico' AND r.column_name IN ('perimetro_cefalico_cm', 'edad_gestacional_semanas')
ON CONFLICT DO NOTHING;
